- name: setup tomcat
  hosts: all
  become: true
  tasks: 
   - name: install java 
     yum:
       name: java
       state: installed
     when: ansible_os_family == "RedHat"

   - name: Install java on ubuntu
     apt:
       name: default-jdk
       state: present
     when: ansible_os_family == "Debian"

   - name: download tomcat packages
     get_url:
       url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.35/bin/apache-tomcat-10.1.35.tar.gz 
       dest: /opt

   - name: untar apache packages
     unarchive: 
       src: /opt/apache-tomcat-10.1.35.tar.gz
       dest: /opt
       remote_src: yes

   - name: add execution permision on startup.sh file
     file:
       path: /opt/apache-tomcat-10.1.35/bin/startup.sh
       mode: 0777

   - name: startup tomcat services
     shell: nohup ./startup.sh
     args:
       chdir: /opt/apache-tomcat-10.1.35/bin/  
